email:
    client:
        account: dicoder@126.com
        host: smtp.126.com
        port: 465
        pwd: "12345"
mysql:
    dbname: z_test
    ip: 127.0.0.1
    port: "3306"
    pwd: 123456
    user: root
server:
    port: "8083"
sqlite:
    db_path: data.db
